<a href="https://colab.research.google.com/github/turxannbiyev13/Python_Fundamentals_Challenges/blob/main/Practice_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
### 1. Numpy kitabxanasını np kimi yukleyin  və versiyasını yoxlayın
import numpy as np
print(np.__version__)

2.0.2


In [2]:
### 2. 0-dan 9-a qədər olan rəqəmlərdən ibarət 1D array yaradın. (Numpy kitaxanasini  arange adin bir method var onun kömeyi ile)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
### 3. 3×3 ölçülü, bütün elementləri True olan bir array  yaradın.
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
### 4 Verilmiş array-da bütün tək rəqəmləri çıxarın.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tek_ededler = arr[arr % 2 != 0]

print(tek_ededler)

[1 3 5 7 9]


In [5]:
### 4 Tək rəqəmləri -1 ilə əvəz edin

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [6]:
### 5 Verilmiş array-dan yalnız müsbət və cüt rəqəmləri çıxarın, nəticəni tərsinə çevirərək ekrana göstərin.
arr = np.array([-10, -2, 0, 3, 4, 8, 15, -5, 12, 20])
filtered = arr[(arr > 0) & (arr % 2 == 0)]
print(filtered[::-1])

[20 12  8  4]


In [7]:
### 6 Verilmiş array-dan  yalnız cüt indekslərdə yerləşən elementləri çıxarın və onların cəmini hesablayın.


arr = np.array([1, 3, 5, 7, 9, 11, 13, 15])


cüt_index = arr[0::2]

cəm = cüt_index.sum()

print(cüt_index)
print(cəm)

[ 1  5  9 13]
28


In [8]:
### 7  1-dən 20-yə qədər rəqəmlərdən ibarət array yaradın, sonra yalnız 5-ə və ya 7-yə bölünən rəqəmləri saxlayaraq yeni massiv yaradın.

arr = np.arange(1, 21)
filtered = arr[(arr % 5 == 0) | (arr % 7 == 0)]
print(filtered)

[ 5  7 10 14 15 20]
